services:
  recipe.api:
    #image: schutzmate/recipeapi
    container_name: recipe.api
    build:
      context: .
      dockerfile: Dockerfile
    #Port 8080 inside the container (from the EXPOSE instruction in the Dockerfile) is mapped to port 5000 on the host machine.
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - DB_HOST=recipe.database
      - DB_NAME=RecipeDb
      - DB_USER=sa
      - DB_PASSWORD=Secret12345!
  
  recipe.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: recipe.database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Secret12345!
    #volumes:
    #lényege hogy mappolod a konténer egy mappáját (ahol a db adatok vannak), a local géped egy mappájára
    #így perzisztálva lesznek az adatok azután hogy ujraindul a konténer
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # Persistent volume for SQL Server data

volumes:
  sqlserver_data: # Named volume declaration
