apiVersion: v1
kind: Service
metadata:
    name: recipe-npservice-srv
spec:
    type: NodePort
    selector:
        app: recipe-api
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
