apiVersion: apps/v1
kind: Deployment
metadata:
    name: recipe-depl
spec:
    selector:
        matchLabels:
            app: recipe-api
    template:
        metadata:
            labels:
                app: recipe-api
        spec:
            containers:
                - name: recipe-api
                  image: schutzmate/recipeapi:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: recipe-clusterip-srv
spec:
    type: ClusterIP
    selector:
        app: recipe-api
    ports:
        - name: recipe-api
          protocol: TCP
          port: 8080
          targetPort: 8080
