apiVersion: apps/v1
kind: Deployment
metadata:
    name: recipe-depl
spec:
    selector:
        matchLabels:
            app: recipe-api
    template:
        metadata:
            labels:
                app: recipe-api
        spec:
            containers:
                - name: recipe-api
                  image: schutzmate/recipeapi:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: recipe-loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: recipe-api
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
